name: AppTemplate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang_format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        clangFormatVersion: 10

  cmake_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.3
      with:
        release: '9-2020-q2'
    - name: Build with CMake for thumbv7e-m
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-G Ninja -D CMAKE_TOOLCHAIN_FILE=cmake/toolchains/armv7e-m.cmake -DCMAKE_SYSTEM_NAME=Generic'
        buildDirectory: '${{ runner.workspace }}/build_thumbv7m'
